// PerChapterBreakdown — table joining funscript.metadata.generated_from
// (chapters[] + recipes[]) with the sidecar for chapter names + content type.
//
// One row per chapter from the funscript's own provenance block. Action
// counts are computed by bucketing the funscript actions array into each
// chapter's [at_ms, end_ms) window. Recipe column summarises the inputs
// videoflow saw at synthesis time so the user can see why each chapter has
// the density it does.

import { useMemo } from 'react';
import {
  chapterDurationMs,
  contentTypeColor,
  contentTypeLabel,
  fmtTime,
} from '../../lib/analysis.js';

const cellStyle = {
  padding: '8px 10px',
  borderBottom: '1px solid var(--border)',
  fontSize: 12,
  verticalAlign: 'middle',
};

const headStyle = {
  ...cellStyle,
  fontSize: 10,
  fontWeight: 700,
  color: 'var(--muted)',
  textTransform: 'uppercase',
  letterSpacing: 1,
  textAlign: 'left',
  background: 'var(--bg)',
};

const monoStyle = {
  fontFamily: 'ui-monospace, monospace',
  color: 'var(--fg)',
};

/** Count actions in each [at_ms, end_ms) chapter window. Linear sweep —
 * relies on actions being sorted by `at` (videoflow guarantees this in
 * export_funscript). */
function actionsPerChapter(actions, chapters) {
  if (!actions?.length || !chapters?.length) return new Array(chapters.length).fill(0);
  const counts = new Array(chapters.length).fill(0);
  let ci = 0;
  for (let i = 0; i < actions.length; i++) {
    const t = actions[i].at;
    while (ci < chapters.length && chapters[ci].end_ms != null && t >= chapters[ci].end_ms) ci++;
    if (ci >= chapters.length) break;
    if (t >= chapters[ci].at_ms) counts[ci]++;
  }
  return counts;
}

function recipeSummary(r) {
  if (!r) return '—';
  const parts = [];
  if (r.source) parts.push(r.source);
  if (r.stroke_density) parts.push(`d=${r.stroke_density}`);
  if (r.tone) parts.push(r.tone);
  if (r.emphasize_beats) parts.push('+downbeats');
  return parts.join(' · ');
}

export default function PerChapterBreakdown({ funscript, sidecar }) {
  const gen = funscript?.metadata?.generated_from || {};
  const chapters = gen.chapters || [];
  const recipes = gen.recipes || [];
  const actions = funscript?.actions || [];
  const sidecarChapters = sidecar?.chapters || [];

  const counts = useMemo(
    () => actionsPerChapter(actions, chapters),
    [actions, chapters],
  );

  if (chapters.length === 0) {
    return (
      <div
        style={{
          padding: 14,
          background: 'var(--bg-elevated)',
          border: '1px solid var(--border)',
          borderRadius: 8,
          fontSize: 12,
          color: 'var(--muted)',
        }}
      >
        This funscript has no <code>metadata.generated_from</code> block —
        per-chapter breakdown unavailable. (Funscripts generated by older
        videoflow versions don't embed provenance.)
      </div>
    );
  }

  return (
    <div
      style={{
        background: 'var(--bg-elevated)',
        border: '1px solid var(--border)',
        borderRadius: 8,
        overflow: 'hidden',
      }}
    >
      <table
        style={{
          width: '100%',
          borderCollapse: 'collapse',
          tableLayout: 'fixed',
        }}
      >
        <colgroup>
          <col style={{ width: 36 }} />
          <col style={{ width: '28%' }} />
          <col style={{ width: 90 }} />
          <col style={{ width: 90 }} />
          <col style={{ width: 80 }} />
          <col />
        </colgroup>
        <thead>
          <tr>
            <th style={headStyle}>#</th>
            <th style={headStyle}>Chapter</th>
            <th style={{ ...headStyle, textAlign: 'right' }}>Window</th>
            <th style={{ ...headStyle, textAlign: 'right' }}>Actions</th>
            <th style={{ ...headStyle, textAlign: 'right' }}>act/s</th>
            <th style={headStyle}>Recipe</th>
          </tr>
        </thead>
        <tbody>
          {chapters.map((c, i) => {
            const sc = sidecarChapters[i];
            const durMs = (c.end_ms ?? 0) - (c.at_ms ?? 0);
            const durSec = durMs / 1000;
            const actCount = counts[i] || 0;
            const actPerSec = durSec > 0 ? actCount / durSec : 0;
            const recipe = recipes[i];
            return (
              <tr key={i}>
                <td
                  style={{
                    ...cellStyle,
                    color: 'var(--muted)',
                    fontFamily: 'ui-monospace, monospace',
                    textAlign: 'center',
                  }}
                >
                  {i + 1}
                </td>
                <td style={cellStyle}>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                    <div style={{ color: 'var(--fg)', fontWeight: 600 }}>
                      {sc?.name || `Chapter ${i + 1}`}
                    </div>
                    {sc && (
                      <div style={{ display: 'flex', gap: 8, alignItems: 'center', fontSize: 11 }}>
                        <span
                          style={{
                            display: 'inline-block',
                            width: 8,
                            height: 8,
                            borderRadius: 2,
                            background: contentTypeColor(sc.content_type),
                          }}
                        />
                        <span style={{ color: 'var(--muted)' }}>
                          {contentTypeLabel(sc.content_type)}
                        </span>
                        <span style={{ color: 'var(--muted)' }}>·</span>
                        <span style={{ ...monoStyle, color: 'var(--muted)' }}>
                          {fmtTime(chapterDurationMs(sc))}
                        </span>
                      </div>
                    )}
                  </div>
                </td>
                <td style={{ ...cellStyle, ...monoStyle, textAlign: 'right', color: 'var(--muted)' }}>
                  {fmtTime(c.at_ms)} – {fmtTime(c.end_ms ?? 0)}
                </td>
                <td style={{ ...cellStyle, ...monoStyle, textAlign: 'right' }}>
                  {actCount.toLocaleString()}
                </td>
                <td style={{ ...cellStyle, ...monoStyle, textAlign: 'right' }}>
                  {actPerSec.toFixed(2)}
                </td>
                <td style={{ ...cellStyle, color: 'var(--muted)', fontSize: 11 }}>
                  {recipeSummary(recipe)}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}
